version: '3.8'

services:

  flask:
    build:
      context: .
      dockerfile: flask.Dockerfile
    command: gunicorn -w 4 --bind 0.0.0.0:5000 wsgi:app
    env_file:
      - ../.env
    volumes:
      - .:/usr/src/app
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    restart: no
    environment:
      POSTGRES_DB: 2dd06_pg
      POSTGRES_USER: 2dd06
      POSTGRES_PASSWORD: uttVEcUemINNCX47
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: